### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by hem1232** [katcosgrove/jfrogcli-action#1]
Run katcosgrove/jfrogcli-action@v1.0.0-beta
  with:
    cmd: ping
  env:
    auth: hemant.choudhari
    apikey: 
    url: 
/usr/bin/docker run --name a6c8cfaf654dbea5c4d[2](https://github.com/hem1232/githubaction/actions/runs/5516434645/jobs/10057792964#step:7:2)fb7dd81018b80910e_a16e[4](https://github.com/hem1232/githubaction/actions/runs/5516434645/jobs/10057792964#step:7:4)[5](https://github.com/hem1232/githubaction/actions/runs/5516434645/jobs/10057792964#step:7:5) --label 2a[6](https://github.com/hem1232/githubaction/actions/runs/5516434645/jobs/10057792964#step:7:6)c8c --workdir /github/workspace --rm -e "auth" -e "apikey" -e "url" -e "INPUT_CMD" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/githubaction/githubaction":"/github/workspace" 2a6c8c:faf654dbea5c4d2fb[7](https://github.com/hem1232/githubaction/actions/runs/5516434645/jobs/10057792964#step:7:7)dd[8](https://github.com/hem1232/githubaction/actions/runs/5516434645/jobs/10057792964#step:7:9)1018b80[9](https://github.com/hem1232/githubaction/actions/runs/5516434645/jobs/10057792964#step:7:10)[10](https://github.com/hem1232/githubaction/actions/runs/5516434645/jobs/10057792964#step:7:11)e  "ping"
Error: Authentication mode must be set!
Running: 'ping'
Error:  the --url option is mandatory
Failure: 'ping' exited with 1

**Comment by katcosgrove** [comment]
Hi. This repo is super old and completely unmaintained. I built it as a stopgap when I worked at JFrog and haven't touched it since they released their own officially maintained version several years ago, which has continued to receive updates. I recommend you go use their official release instead, as I will not be updating this one.

**Comment by hem1232** [comment]
Thanks
